parameters:
  displayName: ''
  gitHubRepoOwner: ''
  gitHubRepoEmail: ''
  GitHubPAT: ''
  gitHubRepo: ''
  gitHubBranch: ''

jobs:
- job: SyncGitHubRepo
  displayName: '${{parameters.displayName}}'
  timeoutInMinutes: 30

  # initiate Azure DevOps Repository Checkout 
  steps:
  - checkout: self
    displayName: 'Checkout Azure DevOps Repository'

  # Setup Git configuration, Working Directory and Artifact directory
  - script: |
      git config --global user.name '${{parameters.gitHubRepoEmail}}'
      git config --global user.email '${{parameters.gitHubRepoOwner}}'
      cp -r $(System.DefaultWorkingDirectory)/* $(System.ArtifactsDirectory)
    displayName: 'Configure Git'

  # Clean and Clone Repository for Sync process
  - script: |
      rm -rf github-repo
      git clone https://${{parameters.GitHubPAT}}@github.com/${{parameters.gitHubRepo}}.git github-repo || { echo "clone failed! Exiting..."; exit 1; }
      cp -r github-repo/.git $(System.ArtifactsDirectory)
      rm -rf github-repo/*
      cp -r $(System.ArtifactsDirectory)/* github-repo/
    displayName: 'Clean and Clone Repository'

  # Start repository Sync process
  - script: |
      cd github-repo
      git add .
      git commit -m "Sync changes from Azure DevOps"
      git push origin '${{parameters.gitHubBranch}}' || { echo "Push failed! Exiting..."; exit 1; }
    displayName: 'Sync GitHub Repository'

