parameters:
  displayName: ''
  scope: ''
  resourceGroupName: ''
  location: ''
  serviceConnection: ''
  subscriptionId: ''
  action: ''
  deploymentFile: ''
  deploymentMode: ''

jobs:
- job: LogAnalyticsWorkspace
  displayName: '${{parameters.displayName}}'
  timeoutInMinutes: 10

  # initiate Azure DevOps Repository Checkout 
  steps:
  - checkout: self
    displayName: 'Checkout Azure DevOps Repository'

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Azure Log Analytics Workspace'
    inputs:
      deploymentScope: '${{parameters.scope}}'
      resourceGroupName: '${{parameters.resourceGroupName}}'
      azureResourceManagerConnection: '${{parameters.serviceConnection}}'
      subscriptionId: '${{parameters.subscriptionId}}'
      action: '${{parameters.action}}'
      location: '${{parameters.location}}'
      csmFile: './infraBlueprints/templates/${{parameters.deploymentFile}}.bicep'
      csmParametersFile: './infraBlueprints/parameters/${{parameters.deploymentFile}}.parameter.json'
      deploymentMode: '${{parameters.deploymentMode}}'
      azureSubscription: '${{parameters.serviceConnection}}' # Input alias: ConnectedServiceName
