parameters:
  displayName: ''
  serviceConnection: ''
#  appType: ''
#  appName: ''
#  tarInstallPath: ''
#  includeRootFolder: ''
#  runtimeStack: ''
#  startUpCommand: ''
#  appFolder: ''
#  archiveFile: ''

jobs:
- job: 'WebAppDeploy'
  displayName: '${{parameters.displayName}}'
  timeoutInMinutes: 30

  # initiate Azure DevOps Repository Checkout 
  steps:
  - checkout: self
    displayName: 'Checkout Azure DevOps Repository'

#  - task: ArchiveFiles@2
#    inputs:
#      rootFolderOrFile: '${{parameters.appFolder}}'
#      includeRootFolder: '${{parameters.includeRootFolder}}'
#      archiveFile: '${{parameters.archiveFile}}'
#    displayName: Build Release Package

#  - task: AzureWebApp@1
#    inputs:
#      azureSubscription: '${{parameters.serviceConnection}}'
#      appType: '${{parameters.appType}}'
#      appName: '${{parameters.appName}}'
#      package: '${{parameters.tarInstallPath}}'
#      runtimeStack: '${{parameters.runtimeStack}}'
#      startUpCommand: '${{parameters.startUpCommand}}'
#    displayName: 'Deploy to Azure Web App'
#    enabled: true

  - task: AzureCLI@2
    inputs:
      azureSubscription: '${{parameters.serviceConnection}}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az webapp create --resource-group "SecureFramework-RG" --plan "SecureFramework-ASP" --name "juiceshop-AS" --deployment-container-image-name bkimminich/juice-shop'
