trigger:
- none

stages:
- stage: ResourceGroup
  pool:
    name: Windows Build and Release ## Linux Build and Release  
  jobs:
  - template: ../releases/rg.release.stage.yml
    parameters:
      displayName: 'Deploying Resource Group'
      scope: 'Subscription'
      subscriptionId: 'ea427d44-e57d-4f51-82bd-d1ab9b57213f'
      location: 'UK South'
      serviceConnection: 'SecureFramework'
      deploymentFile: 'resourceGroups'
      deploymentMode: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'






- stage: GitHubPublishing
  pool:
    name:  Windows Build and Release ## Linux Build and Release ##
  jobs:
  - template: ../releases/github.release.stage.yml
    parameters:
      displayName: 'Publishing To GitHub Repository'
      gitHubRepoOwner: 'Omowale Oseni'
      gitHubRepoEmail: 'omowale.oseni@outlook.com'
      serviceConnectionID: 'e89cdc16-8652-43d1-b6d0-698bb2209232'
      gitHubRepo: 'waleoseni/SecureDevOpsPlatform'
      gitHubBranch: 'main'

