trigger:
- none

stages:
- stage: ResourceGroup
  pool:
    name: Windows Build and Release ## Linux Build and Release  
  jobs:
  - template: ../releases/rg.release.stage.yml
    parameters:
      displayName: 'Deploying Resource Group'
      scope: 'Subscription'
      subscriptionId: '$(subscriptionId)'
      location: 'UK South'
      serviceConnection: 'SecureFramework'
      deploymentFile: 'resourceGroups'
      deploymentMode: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'






- stage: GitHubPublishing
  pool:
    name: Linux Build and Release ## Windows Build and Release ## 
  jobs:
  - template: ../releases/github.release.stage.yml
    parameters:
      displayName: 'Publishing to GitHub Remote Repository'
      gitHubRepoOwner: '$(GITHUB_OWNER)'
      gitHubRepoEmail: '$(GITHUB_EMAIL)'
      GitHubPAT: '$(GITHUB_PAT)'
      gitHubRepo: 'waleoseni/SecureDevOpsPlatform'
      gitHubBranch: 'main'

