trigger:
- none

stages:
- stage: ResourceGroup
  pool:
    name: Windows Build and Release ## Linux Build and Release  
  jobs:
  - template: ../releases/rg.release.stage.yml
    parameters:
      displayName: 'Deploying Resource Group'
      scope: 'Subscription'
      subscriptionId: 'ea427d44-e57d-4f51-82bd-d1ab9b57213f'
      location: 'UK South'
      serviceConnection: 'SecureFramework'
      deploymentFile: 'resourceGroups'
      deploymentMode: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'






- stage: GitHubPublishing
  pool:
    name: Linux Build and Release ## Windows Build and Release ## 
  jobs:
  - template: ../releases/github.release.stage.yml
    parameters:
      displayName: 'Publishing To GitHub Repository'
      gitHubRepoOwner: 'Omowale Oseni'
      gitHubRepoEmail: 'omowale.oseni@outlook.com'
      GitHubPAT: '$(GITHUB_PAT)'
      gitHubServiceConnection: 'GitHubRepositorySecureFramework'
      gitHubRepo: 'waleoseni/SecureDevOpsPlatform'
      gitHubBranch: 'main'

