trigger:
  branches:
    include:
      - main
      - development
      - testing

pool:
  name: Linux Build and Release ## Windows Build and Release ## 

stages:
- stage: resourceGroupDeploy
  jobs:
  - template: ../deployment/resourceGroup.stage.yml
    parameters:
      displayName: 'Deploying Azure Resource Group'
      scope: 'Subscription'
      subscriptionId: '$(subscriptionId)'
      location: 'UK South'
      serviceConnection: 'SecureFramework'
      deploymentFile: 'resourceGroups'
      deploymentMode: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'

- stage: LogAnalyticsWorkspaceDeploy
  dependsOn: resourceGroupDeploy
  jobs:
  - template: ../deployment/logAnalyticsWorkspace.stage.yml
    parameters:
      displayName: 'Deploying Log Analytics Workspace'
      scope: 'resourceGroup'
      resourceGroupName: 'SecureFramework-RG'
      subscriptionId: '$(subscriptionId)'
      action: 'Create Or Update Resource Group'
      location: 'UK South'
      serviceConnection: 'SecureFramework'
      deploymentFile: 'logAnalyticsWorkspace'
      deploymentMode: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'






- stage: SyncGitHubRepo
  jobs:
  - template: ../deployment/githubSync.stage.yml
    parameters:
      displayName: 'Syncing Azure DevOps to GitHub Repository'
      gitHubRepoOwner: '$(GITHUB_OWNER)'
      gitHubRepoEmail: '$(GITHUB_EMAIL)'
      GitHubPAT: '$(GITHUB_PAT)'
      gitHubRepo: 'waleoseni/SecureDevOpsPlatform'
      gitHubBranch: 'main'

