trigger:
  branches:
    include:
      - main
      - development
      - testing

stages:
- stage: deployResourceGroup
  pool:
    name: Linux Build and Release ## Windows Build and Release ## 
  jobs:
  - template: ../deployment/resourceGroup.release.stage.yml
    parameters:
      displayName: 'Deploying Azure Resource Group'
      scope: 'Subscription'
      subscriptionId: '$(subscriptionId)'
      location: 'UK South'
      serviceConnection: 'SecureFramework'
      deploymentFile: 'resourceGroups'
      deploymentMode: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'






- stage: SyncGitHubRepo
  pool:
    name: Linux Build and Release ## Windows Build and Release ## 
  jobs:
  - template: ../deployment/githubSync.release.stage.yml
    parameters:
      displayName: 'Syncing Azure DevOps to GitHub Repository'
      gitHubRepoOwner: '$(GITHUB_OWNER)'
      gitHubRepoEmail: '$(GITHUB_EMAIL)'
      GitHubPAT: '$(GITHUB_PAT)'
      gitHubRepo: 'waleoseni/SecureDevOpsPlatform'
      gitHubBranch: 'main'

