trigger:
  - none

pool:
  name: Linux Build and Release ## Windows Build and Release ## 

stages:
- stage: destroyResourceGroup
  jobs:
  - template: ../deployment/resourceGroup.cleanup.yml
    parameters:
      displayName: 'Deleting Azure Resource Group and Resources'
      serviceConnection: 'SecureFramework'
      subscriptionId: '$(SUBSCRIPTIONID)'
      action: DeleteRG
      resourceGroupName: 'SecureFramework-RG'


#- stage: destroyResourceGroup
#  jobs:
#  - template: ../deployment/resourceGroup.cleanup.yml
#    parameters:
#      displayName: 'Deleting Azure Resource Group and Resources'
#      serviceConnection: 'SecureFramework'
#      resourceGroupName: 'SecureFramework-RG'
