trigger:
  - none

resources:
  pipelines:
    - pipeline: SecurePlatform
      project: SecureDevOpsPlatform
      source: SecurePlatform
      trigger: none

pool:
  name: Linux Build and Release ## Windows Build and Release ## 

stages:
- stage: SonarQubeSecurityScan
  jobs:
  - template: ../securityValidation/sonarQube.stage.yml
    parameters:
      displayName: 'SonarQube: Security Scan and Analysis'
      sonarQubeSecureConnection: 'SonarQubeSecureFramework'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: '$(SONARQUBE_PROJECTKEY)'
      cliProjectName: 'sonar.secure.codeAnalysis'
      cliSources: 'juice-shop_17.1.1'


