trigger:
  branches:
    include:
      - AzurePipeline   # main
      - development
      - testing

pool:
  name: Linux Build and Release ## Windows Build and Release ## 

stages:
- stage: ResourceGroup
  jobs:
  - template: ../deployment/resourceGroup.stage.yml
    parameters:
      displayName: 'Deploying Azure Resource Group'
      scope: 'Subscription'
      subscriptionId: '$(subscriptionId)'
      location: 'UK South'
      serviceConnection: 'SecureFramework'
      deploymentFile: 'resourceGroups'
      deploymentMode: 'Incremental'  # 'Incremental' | 'Complete' | 'Validation'
