parameters:
  displayName: ''
  sonarQubeSecureConnection: ''
  scannerMode: ''
  configMode: ''
  cliProjectKey: ''
  cliProjectName: ''
  cliSources: ''

jobs:
- job: 'SonarQubeConfigAnalysis'
  displayName: '${{parameters.displayName}}'
  timeoutInMinutes: 30

  # initiate Azure DevOps Repository Checkout 
  steps:
  - checkout: self
    displayName: 'Checkout Azure DevOps Repository'
  
  - task: SonarQubePrepare@7
    inputs:
      SonarQube: '${{parameters.sonarQubeSecureConnection}}'
      scannerMode: '${{parameters.scannerMode}}'
      configMode: '${{parameters.configMode}}'
      cliProjectKey: '${{parameters.cliProjectKey}}'
      cliProjectName: '${{parameters.cliProjectName}}'
      cliSources: '$(System.DefaultWorkingDirectory)/examples/${{parameters.cliSources}}'
    displayName: 'Prepare Analysis Configuration'
      
  - task: SonarQubeAnalyze@7
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
    displayName: 'Secure Code Analysis'

  - task: SonarQubePublish@7
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Analysis'



#  # initiate Azure DevOps Repository Checkout 
#  steps:
#  - checkout: self
#    displayName: 'Checkout Azure DevOps Repository'
#
#  # Delete the resource group using Azure CLI
#  - task: AzureCLI@2
#    displayName: 'Delete Resource Group'
#    inputs:
#      azureSubscription: '${{parameters.serviceConnection}}'
#      scriptType: bash
#      scriptLocation: inlineScript
#      inlineScript: |
#        echo 'Deleting Resource Group: ${{parameters.resourceGroupName}}'
#        az group delete --name ${{parameters.resourceGroupName}} --yes    ## --no-wait
#        echo 'Resource group deletion initiated.'

