parameters:
  displayName: ''
  gitHubRepoOwner: ''
  gitHubRepoEmail: ''
  GitHubPAT: ''
  gitHubRepo: ''
  gitHubBranch: ''

jobs:
- job: GitHubPublishing
  displayName: '${{parameters.displayName}}'
  timeoutInMinutes: 10

  steps:
  - checkout: self
    displayName: 'Checkout Azure DevOps Repository'
 
  - script: |
      git config --global user.name '${{parameters.gitHubRepoEmail}}'
      git config --global user.email '${{parameters.gitHubRepoOwner}}'

         # Copy all files to the artifact directory
      cp -r $(System.DefaultWorkingDirectory)/* $(System.ArtifactsDirectory)

         # Clone the GitHub repository
      git clone https://${{parameters.GitHubPAT}}@github.com/${{parameters.gitHubRepo}}.git github-repo ||
      { echo "clone failed! Exiting..."; exit 1; }

         # Remove all files in the GitHub repo folder except .git
         # find github-repo -mindepth 1 -not -name '.git' -exec rm -rf {} +

         # Copy all files from Azure DevOps to the GitHub repo folder
      cp -r $(System.ArtifactsDirectory)/* github-repo/

         # Change directory to the GitHub repo
      cd github-repo

         # Stage, commit, and push changes
      git add .
      git commit -m "Sync changes from Azure DevOps"
      git push origin '${{parameters.gitHubBranch}}' || { echo "Push failed! Exiting..."; exit 1; }

    displayName: 'Push to GitHub'

