parameters:
  displayName: ''
  gitHubRepoOwner: ''
  gitHubRepoEmail: ''
  serviceConnectionID: ''
  gitHubRepo: ''
  gitHubBranch: ''

jobs:
- job: GitHubPublishing
  displayName: 'Publishing To GitHub Repository'
  timeoutInMinutes: 10

  steps:
  # Step 1: Set up Git configuration
  - script: |
      git config --global user.email '${{parameters.gitHubRepoOwner}}'
      git config --global user.name '${{parameters.gitHubRepoEmail}}'
    displayName: 'Configure Git'

  # Step 2: Clone the GitHub repository using the service connection
  - task: CmdLine@2
    displayName: 'Clone GitHub repository'
    inputs:
      script: |
        git clone -b ${{parameters.gitHubBranch}} https://$(ACCESS_TOKEN):x-oauth-basic@github.com/${{parameters.gitHubRepo}}.git github-repo
    env:
      ACCESS_TOKEN: $(serviceConnections.${{parameters.serviceConnectionID}}.parameters.AccessToken)

  # Step 3: Copy files to the GitHub repository
  - script: |
      rsync -av --progress $(System.DefaultWorkingDirectory)/ github-repo/ --exclude=github-repo
      cd github-repo
      git checkout ${{parameters.gitHubBranch}} || git checkout -b ${{parameters.gitHubBranch}}
      git add .
      git commit -m "Update from Azure DevOps pipeline"
      git push origin '${{parameters.gitHubBranch}}'
    displayName: 'Push changes to GitHub'
    env:
      ACCESS_TOKEN: $(serviceConnections.${{parameters.serviceConnectionID}}.parameters.AccessToken)



