parameters:
  displayName: ''
  gitHubRepoOwner: ''
  gitHubRepoEmail: ''
  GitHubPAT: ''
  gitHubRepo: ''
  gitHubBranch: ''

jobs:
- job: GitHubPublishing
  displayName: '${{parameters.displayName}}'
  timeoutInMinutes: 10

  steps:
  - checkout: self
    displayName: 'Checkout Azure DevOps Repository'
 
  - script: |
      git config --global user.name '${{parameters.gitHubRepoEmail}}'
      git config --global user.email '${{parameters.gitHubRepoOwner}}'
      # Clone the GitHub repository
      git clone https://${{parameters.GitHubPAT}}@github.com/${{parameters.gitHubRepo}}.git github-clean-repo || { echo "clone failed! Exiting..."; exit 1; }
      # Change directory to the github-clean-repo
      cd github-clean-repo
      # Clean up GitHub repository
      rm -rf *
      # push Cleaned GitHub repository
      git add -A
      git commit -m "Remove all repository content"
      git push origin '${{parameters.gitHubBranch}}' || { echo "Push failed! Exiting..."; exit 1; }
    displayName: 'Clean GitHub Repository'

  - script: |
      git config --global user.name '${{parameters.gitHubRepoEmail}}'
      git config --global user.email '${{parameters.gitHubRepoOwner}}'
      # Clean up the cloned repository
      rm -rf github-repo
      # Copy all files from Working Directory to the Artifact directory
      cp -r $(System.DefaultWorkingDirectory)/* $(System.ArtifactsDirectory)
      # Clone the GitHub repository
      git clone https://${{parameters.GitHubPAT}}@github.com/${{parameters.gitHubRepo}}.git github-repo || { echo "clone failed! Exiting..."; exit 1; }
      # Copy all files from Azure DevOps to the GitHub repo folder
      cp -r $(System.ArtifactsDirectory)/* github-repo/
      # Change directory to the GitHub repo
      cd github-repo
      # Clean up the cloned repository
      rm -rf github-clean-repo
      # Stage, commit, and push changes
      git add .
      git commit -m "Sync changes from Azure DevOps"
      git push origin '${{parameters.gitHubBranch}}' || { echo "Push failed! Exiting..."; exit 1; }
    displayName: 'Sync GitHub Repository'

